### ISSUE TITLE
go-ds-versioning error when trying to migrate new datastore

### ISSUE THREAD

**Issue by gmelodie** [application-research/estuary#158]
I'm getting the following error when trying to build from the latest master. Not sure what changed between the last time I built estuary last week and now, probably a bug in some dependency.
```
➜  estuary git:(master) ✗ make estuary && ./estuary --datadir=mydatadir --logging 2>&1 | tee estuary.log 
go build 
2022-04-18T11:21:05.652-0300	DEBUG	estuary	estuary/main.go:161	Flag datadir is set to mydatadir
2022-04-18T11:21:05.653-0300	DEBUG	estuary	estuary/main.go:161	Flag logging is set to true
Wallet address is:  f1pbk3nxyewrbsdxxmrzyq4btd5moxdl7k7i7i2dq
2022-04-18T11:21:06.401-0300	INFO	dt-impl	impl/impl.go:145	start data-transfer module
/ip4/10.0.0.4/tcp/6744/p2p/12D3KooWSjcfenYRqMDy77dR9LpfnH5NFNJKqDxGHzMaqib7PUDA
/ip4/127.0.0.1/tcp/6744/p2p/12D3KooWSjcfenYRqMDy77dR9LpfnH5NFNJKqDxGHzMaqib7PUDA
2022-04-18T11:21:06.403-0300	INFO	estuary	estuary/replication.go:719	queueing all content for checking: 0
panic: runtime error: index out of range [0] with length 0

goroutine 3588 [running]:
github.com/filecoin-project/go-ds-versioning/internal/migrate.To({0x41af328, 0xc00005a0c8}, {0x41dcf50, 0xc0002adb00}, {0x0, 0x1b717f7, 0x0}, {0x3f23980, 0x1})
	/home/gmelodi/go/pkg/mod/github.com/filecoin-project/go-ds-versioning@v0.1.1/internal/migrate/migrate.go:111 +0x4c6
github.com/filecoin-project/go-ds-versioning/internal/runner.(*Runner).Migrate.func1.1()
	/home/gmelodi/go/pkg/mod/github.com/filecoin-project/go-ds-versioning@v0.1.1/internal/runner/runner.go:45 +0x57
sync.(*Once).doSlow(0x683205, 0xc000056b40)
	/usr/local/go/src/sync/once.go:68 +0xd2
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:59
github.com/filecoin-project/go-ds-versioning/internal/runner.(*Runner).Migrate.func1()
	/home/gmelodi/go/pkg/mod/github.com/filecoin-project/go-ds-versioning@v0.1.1/internal/runner/runner.go:44 +0x59
created by github.com/filecoin-project/go-ds-versioning/internal/runner.(*Runner).Migrate
	/home/gmelodi/go/pkg/mod/github.com/filecoin-project/go-ds-versioning@v0.1.1/internal/runner/runner.go:43 +0xb2
```

**Comment by brendalee** [comment]
@gmelodie are you still seeing this issue? If not, can. you comment and close?

**Comment by gmelodie** [comment]
Fixed by https://github.com/filecoin-project/go-ds-versioning/pull/6
